name: Refactor Rector

on:
    push:
      branches:
        - 'rilis-dev-7344'     
      paths:
        - '.github/workflows/refactor-rector.yml'
        - 'donjo-app/**'
        - 'app/**'   

jobs:
    rector:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}        
          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: 8.2
                
          -   run: composer global require rector/rector
          - name: Rector Cache
            uses: actions/cache@v3
            with:
              path: .cache-rector
              key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
              restore-keys: ${{ runner.os }}-rector-          
          -   run: rector process --ansi

          # commit changes, see https://github.com/EndBug/add-and-commit
          -
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: '[code-refactor] Rector Refactor Code'
